apiVersion: v2
name: todo-chart
description: A Helm chart for Phase IV Todo Application
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - todo
  - ai
  - chatbot
  - kubernetes
maintainers:
  - name: Rameez Qadir
    email: rameezfudda@gmail.com
